import { useEffect,useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import { api } from '../services';
const steps=[['extract','Extracting job requirements'],['crawl','Researching company website'],['discussion','Looking for public interview discussion'],['brief','Building company brief'],['questions','Generating targeted questions'],['coverage','Checking question coverage'],['flashcards','Creating flashcards'],['schedule','Building study schedule'],['validate','Validating kit']];
export function Generating(){
 const{id}=useParams();const nav=useNavigate();const[state,setState]=useState<any>(null);const[error,setError]=useState('');
 useEffect(()=>{let active=true;const poll=async()=>{try{const r=await api.get(`/api/kits/${id}/status`);if(!active)return;setState(r.data);if(r.data.status==='ready'){nav(`/kits/${id}`);return}if(r.data.status==='failed'){setError(r.data.generation?.error||'Generation failed.');return}setTimeout(poll,1500)}catch(e:any){if(active)setError(e.response?.data?.message||'Unable to read generation status.')}};poll();return()=>{active=false}},[id,nav]);
 const current=state?.generation?.step;const currentIndex=steps.findIndex(s=>s[0]===current);const progress=currentIndex<0?8:Math.round(((currentIndex+1)/steps.length)*100);
 return <main className="relative min-h-screen overflow-hidden bg-slate-950 text-white"><div className="pointer-events-none absolute -right-24 -top-20 h-80 w-80 rounded-full bg-cyan-400/15 blur-3xl"></div><div className="pointer-events-none absolute -bottom-20 -left-20 h-72 w-72 rounded-full bg-violet-500/10 blur-3xl"></div>
  <section className="relative mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-20">
   <div className="mb-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-2xl text-cyan-300">✦</div><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Building your kit</p><h1 className="mt-3 break-words text-3xl font-bold tracking-tight sm:text-5xl">Research first. Generate second.</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-300">PrepKit is working through the role, company research, questions, coverage and schedule. You can review everything when it is ready.</p></div>
   <div className="mb-7 rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-xs font-semibold text-slate-400"><span>Generation progress</span><span className="text-cyan-300">{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300 transition-all duration-500" style={{width:`${progress}%`}}/></div></div>
   <div className="space-y-2">{steps.map(([key,label],i)=>{const done=i<currentIndex;const active=i===currentIndex;return <div key={key} className={`flex items-center gap-4 rounded-2xl border p-4 transition ${active?'border-cyan-300/30 bg-cyan-300/10':'border-white/10 bg-white/[.04]'}`}><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full border text-sm font-bold ${done?'border-emerald-300/40 bg-emerald-300/10 text-emerald-300':active?'border-cyan-300 bg-cyan-300 text-slate-950':'border-white/10 text-slate-500'}`}>{done?'✓':active?'•':i+1}</div><span className={`text-sm ${done||active?'font-semibold text-white':'text-slate-500'}`}>{label}</span>{active&&<span className="ml-auto h-2 w-2 animate-pulse rounded-full bg-cyan-300"></span>}</div>})}</div>
   {error&&<div className="mt-6 rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}
  </section>
 </main>
}
